[versions]
agp = "9.0.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
sonar = "7.2.2.6593"
robolectric = "4.16.1"
protobuf = "4.33.5"
jdom = "2.0.6.1"
netty = "4.2.10.Final"
jose4j = "0.9.6"
commonsLang3 = "3.20.0"
httpclient = "4.5.14"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
protobuf-kotlin = { group = "com.google.protobuf", name = "protobuf-kotlin", version.ref = "protobuf" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf" }
jdom2 = { group = "org.jdom", name = "jdom2", version.ref = "jdom" }
netty-common = { group = "io.netty", name = "netty-common", version.ref = "netty" }
netty-handler = { group = "io.netty", name = "netty-handler", version.ref = "netty" }
netty-codec-http = { group = "io.netty", name = "netty-codec-http", version.ref = "netty" }
netty-codec-http2 = { group = "io.netty", name = "netty-codec-http2", version.ref = "netty" }
jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version.ref = "jose4j" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang3" }
httpclient = { group = "org.apache.httpcomponents", name = "httpclient", version.ref = "httpclient" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
sonar = { id = "org.sonarqube", version.ref = "sonar" }
